### PR TITLE
Implemented get_server_publickey, added null check to get_issue_banner

### PR DESCRIPTION
**Pull request by cinerieus**

### CODE REVIEW

**Comment by pkittenis** [comment]
Hi there,

Thanks for the PR! 

Changes look good, thanks. Cython sources will need re-generating, see comment in code.

**Comment by cinerieus** [comment]
Hi, no problem!

Had some issues merging with latest commit but should be sorted now. I've recompiled the session.pyx as well.

**Comment by pkittenis** [comment]
Yeah, also had to re-generate C files. They're auto-generated so not a big problem.

Can you add a test for the changes as well, then this can be merged. Can refer to [existing session tests](https://github.com/ParallelSSH/ssh-python/blob/master/tests/test_session.py) for examples.

Thanks again for the PR.

**Comment by cinerieus** [comment]
All done.

**Pull request merged**
